
import java.awt.Color;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Leonardo Olvera <UMSNH>
 */
public class Principal extends javax.swing.JFrame {
   
public String nombre;
public int edad;
public int peso;
public int estatura;

public int r1=-1;
public int r2=-1;
public int r3=-1;
public int r4=-1;
public int r5=-1;
public int r6=-1;
public int r7=-1;


    /**
     * Creates new form Principal
     */
    public Principal() {
        setResizable(false);
        initComponents();
        this.setLocationRelativeTo(null);
        jTextAreaRecomendacion.setLineWrap(true);
        jTextAreaRecomendacion.setWrapStyleWord(true);
        jTextAreaDetalle.setLineWrap(true);
        jTextAreaDetalle.setWrapStyleWord(true);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jlblnombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPeso = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldAltura = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextFieldEdad = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        botonC = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldProbabilidad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldRiesgo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldMasaCorporal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaRecomendacion = new javax.swing.JTextArea();
        jLabelCalculo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDetalle = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButtonCalcular = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jlblnombre.setForeground(new java.awt.Color(255, 255, 255));
        jlblnombre.setText("Nombre:");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Edad:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sexo:");

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer" }));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Peso:");

        jTextFieldPeso.setToolTipText("");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kg");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Estatura:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cm");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1904674-accept-approved-check-checked-confirm-done-tick_122524.png"))); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Ej. 80");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Ej. 175");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jlblnombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldEdad)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel14)
                                .addGap(130, 130, 130)
                                .addComponent(jLabel15)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblnombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jTextFieldAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)))
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addContainerGap())))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sintomas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Hola, porfavor haz clic en el siguiente botón para iniciar el cuestionario");

        botonC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuestionario.png"))); // NOI18N
        botonC.setText("Iniciar cuestionario");
        botonC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(111, 111, 111))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(botonC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonC)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Probabilidad de tener diabetes:");

        jTextFieldProbabilidad.setEditable(false);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Por lo tanto su riesgo es:");

        jTextFieldRiesgo.setEditable(false);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Masa corporal:");

        jTextFieldMasaCorporal.setEditable(false);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Recomendaciones:");

        jTextAreaRecomendacion.setEditable(false);
        jTextAreaRecomendacion.setColumns(20);
        jTextAreaRecomendacion.setRows(5);
        jScrollPane1.setViewportView(jTextAreaRecomendacion);

        jLabelCalculo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCalculo.setText("De acuerdo a  su información, su resultado es: ");

        jTextAreaDetalle.setEditable(false);
        jTextAreaDetalle.setColumns(20);
        jTextAreaDetalle.setRows(5);
        jScrollPane2.setViewportView(jTextAreaDetalle);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Explicación:");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("%");

        jButtonCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calculating_118429.png"))); // NOI18N
        jButtonCalcular.setText("Calcular");
        jButtonCalcular.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCalcular.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/4115235-exit-logout-sign-out_114030.png"))); // NOI18N
        jButton2.setText("Salir");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/36_104857.png"))); // NOI18N
        jButton3.setText("Limpiar");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldMasaCorporal)
                                .addComponent(jTextFieldRiesgo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jTextFieldProbabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12))))
                    .addComponent(jLabelCalculo))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jButtonCalcular)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton2))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabelCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldMasaCorporal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldProbabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldRiesgo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCalcular)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCMouseClicked
    if(nombre==null || edad==0|| peso==0|| peso==0){
    JOptionPane.showMessageDialog(botonC,"Primero llene los datos de usuario");
} else{
        
        String[ ] opciones = {"sí", "no"};
       JOptionPane.showMessageDialog(botonC, "Por favor, conteste las siguientes preguntas");
        r1 = JOptionPane.showOptionDialog(botonC, "¿Ha orinado con mas frecuencia de lo común?", "Elección:",JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,null, opciones, null);
        r2 = JOptionPane.showOptionDialog(botonC, "¿Se ha sentido mas fatigado de lo normal?", "Elección:",JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,null, opciones, null);
        r3 =  JOptionPane.showOptionDialog(botonC, "¿Ha sentido entumecimiento en sus manos u otras extremidades?", "Elección:",JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,null, opciones, null);
        r4= JOptionPane.showOptionDialog(botonC, "¿Ha tenido un aumento irregular de apetito?", "Elección:",JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,null, opciones, null);
        r5 = JOptionPane.showOptionDialog(botonC, "¿Ha tenido la visión borrosa últimamente?", "Elección:",JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,null, opciones, null);
       
        r6 = JOptionPane.showOptionDialog(botonC, "¿Tiene algún familiar con problemas de diabetes?", "Elección:",JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,null, opciones, null);
        if(r6 == 0){
             r7 = JOptionPane.showOptionDialog(botonC, "¿Dicho familiar pertenece a su línea ascendente (padres/abuelos)?", "Elección:",JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,null, opciones, null);
             if(r7 == 0){
                 r6 = 0;
             }else{
                 r6=1;
             }
        }
       
        JOptionPane.showMessageDialog(botonC,"Muchas gracias, por favor, ahora presione el botón 'calcular' de la siguiente sección.");
    }
    }//GEN-LAST:event_botonCMouseClicked

    public double prob(int r1, int r2, int r3, int r4, int r5, int r6){
        
        double contador = 0;
        
        if(r1 == 0){
            contador = contador + 60*1/4;
        }else{
            contador = contador + 0;
        }
        
        if(r2==0){
            contador = contador + 40*1/4;
        }else{
            contador = contador + 0;
        }
       
        if(r3==0){
            contador = contador + 40*1/4;
        }else{
            contador = contador + 0;
        }
        
        
        if(r4==0){
            contador = contador + 40*1/4;
        }else{
            contador = contador + 0;
        }
        
        if(r5==0){
            contador = contador + 40*1/4;
        }else{
            contador = contador + 0;
        }
        
        if(r6==0){
            contador = contador + 60*1/4;
        }else{
            contador = contador + 0;
        }
        
        
        if(Integer.parseInt(jTextFieldEdad.getText())>=45){
            contador = contador + 60*1/4;
        }else{
            contador = contador + 0;
        }
        
       /* if(jTextFieldEdad.getText().equals("45")){
            contador = contador + 60*1/4;
        }else{
            contador = contador + 0;
        }*/
        
        double res = (double) peso/(estatura*estatura);
        double masa2 = res *100;
        
        if(masa2 >= 0.30){
            contador = contador + 60*1/4;
        }else{
            contador = contador + 0;
        }
        
        
        return contador;
    }
    
    
    public String Risk(double probabilidad){
        
        String resultado = null;
        if(probabilidad >= 70){
            resultado = "Alto";
        }else{
            if(probabilidad >= 45 && probabilidad < 70){
                resultado = "Medio";
            }else{
                resultado = "Bajo";
            }
        }
        return resultado;
    }
    
  public String Recom(double probabilidad){
      String resultado = null;
      if(probabilidad >= 70){
            resultado = "CUIDADO! se le recomienda que visite a su médico, si bien la detección de diabetes requiere de pruebas de glucosa en sangre y otras pruebas es probable que pueda presentar la enfermedad, por lo cual se "
                    + "recomienda que baje de peso, elimine los azúcares de su dieta y principalmente que haga mas ejercicio.";
        }else{
            if(probabilidad >= 45 && probabilidad < 70){
                resultado = "No baje la guardia! se le recomienda relizarse chequeos medicos con frecuencia, a pesar de que sus datos de probabilidad no son muy altos aun tiene factores que en futuro podrían "
                        + "desencadenar dicha enfermedad, por  lo cual se recomienda manetener y adoptar habitos saludables de alimentación y ejercicio.";
            }else{
                resultado = "Presenta baja probabilidad de tener la enfermedad, pero aun así se le invita a seguir con hábitos saludabes de alimentación"
                        + "ademas de realiza chequeos médicos para descartar cualquier otro sintoma.";
            }
        }
        return resultado;
  }  
    
  
  public String Explic(int edad,double masa, int r1, int r2, int r3, int r4, int r5, int r6){
      String resultado;
      String tedad;
      String resfam;
      String resmas;
      
      if(edad >=45){
          tedad = "Es igual o superior a 45 años, por lo cual se aumenta la probabilidad de padecimiento, debido a que con frecuencia en esta edad hay cambios en la producción y segregación de insulina por el páncreas.";
      }else{
          tedad ="Es menor de 45 años, por lo tanto tiene menos probabilidad de padecimiento, debido a que aún no hay muchos cambios en las funciones del páncreas.";
      }
      
      int contador = 0;//este if para contar el numero de sitomas que tiene el paciente
        
        if(r1 == 0){
            contador = contador + 1;
        }else{
            contador = contador + 0;
        }
        
        if(r2==0){
            contador = contador + 1;
        }else{
            contador = contador + 0;
        }
       
        if(r3==0){
            contador = contador + 1;
        }else{
            contador = contador + 0;
        }
        
        
        if(r4==0){
            contador = contador + 1;
        }else{
            contador = contador + 0;
        }
        
        if(r5==0){
            contador = contador + 1;
        }else{
            contador = contador + 0;
        }
        
        //aquí termina
      
       if(r6 == 0){
           resfam = "Usted tiene familiares en línea recta ascendente con dicha enfermedad, lo cual causa que por factores genéticos tenga mas probabilidad de adquirir la enfermedad.";
       } else{
           resfam="Usted no tiene familiares en línea recta ascendente con la enfermedad, lo cual ayuda por factores genéticos a que tenga menos probabilidad de padecerla.";
       }
        
       double res = (double) peso/(estatura*estatura);
        double masa3 = res * 100;
        
        if(masa3 >= 0.30){
            resmas = "Usted tiene igual o mas de 30 IMS lo cual representa obesidad con un gran riesgo de contraer diabetes.";
        }else{
          if(masa3 >=0.25 && masa3 < 0.30){
              resmas = "Usted tiene entre 25 y 30 IMS, lo cual representa obesidad, con leve probabilidad de padecer la enfermedad.";
          }else{
              resmas = "Usted tiene menos de 25 IMS, el cual es un buen nivel de salud (aunque no necesariamente le evita de padecer esta u otras enfermedades).";
          }
        }
        
       
      resultado = 
                 nombre+" de acuerdo a que:\n"
                +"\n Edad: " +tedad + "\n "
                +"\n Sintomas: "+ "Usted padece "+contador+" sintomas de los 5 sintomas mas comunes asociados a la diabetes (provocados por los cambios de la segregación de insulina del páncreas en el cuerpo)."+ "\n "
                +"\n Factores geneticos: "+resfam+ "\n "
                +"\n Masa corporal: " +resmas+ "\n "
              ;
      
      
      
      return resultado;
  }
  
  
  
    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        // TODO add your handling code here:
     
        //jTextFieldMasaCorporal.setText(String.valueOf((double)(peso/(estatura*estatura))*100));
        
        /*double res = (double) peso/(estatura*estatura);
        double masa = res *100;
        jTextFieldMasaCorporal.setText(String.valueOf(masa));*/
        
          if(r1 == -1 || r2 == -1 || r3 == -1 || r4 == -1 || r5 == -1 || r6 ==-1){
    JOptionPane.showMessageDialog(jButtonCalcular,"Primero conteste el cuestinario");
}else{
        
        
        JOptionPane.showMessageDialog(jButtonCalcular, "Nota: Este sistema se basa en probabilidad, por lo cual no se deben tomar los resultados como un diagnostico exacto. ");
        double res = (double) peso/(estatura*estatura); 
        double masa = res *100;
        jTextFieldMasaCorporal.setText( String.valueOf(String.format("%.2f", masa*100)));
        
        
        jTextFieldProbabilidad.setText(String.valueOf(prob(r1, r2, r3, r4, r5, r6)));
        
        jTextFieldRiesgo.setText(Risk(prob(r1, r2, r3, r4, r5, r6)));
        
        if(Risk(prob(r1, r2, r3, r4, r5, r6)).equals("Alto")){
              jTextFieldRiesgo.setBackground(Color.RED);
        }else{
            if(Risk(prob(r1, r2, r3, r4, r5, r6)).equals("Medio")){
                jTextFieldRiesgo.setBackground(Color.ORANGE);
            }else{
                jTextFieldRiesgo.setBackground(Color.GREEN);
            }
        }
        
        jTextAreaRecomendacion.setText(Recom(prob(r1, r2, r3, r4, r5, r6)));
        
        jTextAreaDetalle.setText(Explic(edad, masa, r1, r2, r3, r4, r5, r6));
               
        
   
        
    }//GEN-LAST:event_jButtonCalcularActionPerformed
    }
    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

if(jTextFieldNombre.getText().equals("") || jTextFieldEdad.getText().equals("")|| jTextFieldPeso.getText().equals("")|| jTextFieldAltura.getText().equals("")){
    JOptionPane.showMessageDialog(jButton1,"Primero llene los datos de usuario");
}else{


        nombre= jTextFieldNombre.getText();
        edad = Integer.parseInt(jTextFieldEdad.getText());
        peso = Integer.parseInt(jTextFieldPeso.getText());
        estatura = Integer.parseInt(jTextFieldAltura.getText());
       
        JOptionPane.showMessageDialog(botonC, "Muchas gracias, ahora porfavor de clic en 'Iniciar cuestionario' en la siguiente sección");
    }//GEN-LAST:event_jButton1MouseClicked
    }
    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        jTextFieldNombre.setText("");
        nombre=null;
        jTextFieldPeso.setText("");
        peso=0;
        jTextFieldEdad.setText("");
        edad=0;
        jTextFieldAltura.setText("");
        estatura=0;
        jTextFieldMasaCorporal.setText("");
        jTextFieldProbabilidad.setText("");
        jTextFieldRiesgo.setText("");
        jTextAreaRecomendacion.setText("");
        jTextAreaDetalle.setText("");
        jTextFieldRiesgo.setBackground(Color.WHITE);
        r1=-1;
        r2=-1;
        r3=-1;
        r4=-1;
        r5=-1;
        r6=-1;
        r7=-1;
    }//GEN-LAST:event_jButton3MouseClicked

    
    
        
   
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        JOptionPane.showMessageDialog(null, "Hola, bienvenido a este sistema de detección de diabetes");
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonC;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCalculo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaDetalle;
    private javax.swing.JTextArea jTextAreaRecomendacion;
    private javax.swing.JTextField jTextFieldAltura;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldMasaCorporal;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPeso;
    private javax.swing.JTextField jTextFieldProbabilidad;
    private javax.swing.JTextField jTextFieldRiesgo;
    private javax.swing.JLabel jlblnombre;
    // End of variables declaration//GEN-END:variables
}
